import { STATUS_GROUP } from './../enums/main';

// Fron End status mapping, maybe in future pull from api service
export const checkStatusMapping  = {
    'N': {btnClass: 'btn-danger'},
    'RO': {btnClass: 'btn-warning'},
    'A': {btnClass: 'btn-info'},
    'OC': {btnClass: 'btn-warning'},
    'SD': {btnClass: 'btn-warning'},
    'RI': {btnClass: 'btn-warning'},
    'ER': {btnClass: 'btn-warning'},
    'OP': {btnClass: 'btn-warning'},
    'iST': {btnClass: 'btn-warning'},
    'SOA': {btnClass: 'btn-warning'},
    'fST': {btnClass: 'btn-success'},
    'POA': {btnClass: 'btn-success'},
    'MP': {btnClass: 'btn-info'},
    'PCF': {btnClass: 'btn-info'},
    'PWC': {btnClass: 'btn-success'},
    'PWA': {btnClass: 'btn-success'},
    'PNR': {btnClass: 'btn-success'},
    'PNC': {btnClass: 'btn-success'},
    'PA': {btnClass: 'btn-success'},
    'PW': {btnClass: 'btn-success'},
    'PC': {btnClass: 'btn-success'},
    'PP': {btnClass: 'btn-success'},
    'PT': {btnClass: 'btn-success'},
    'PI': {btnClass: 'btn-success'},
    'PIA': {btnClass: 'btn-success'},
    'FD': {btnClass: 'btn-warning'},
    'FR': {btnClass: 'btn-warning'},
    'FS': {btnClass: 'btn-warning'},
    'FG': {btnClass: 'btn-warning'},
    'VI': {btnClass: 'btn-warning'},
    'VC': {btnClass: 'btn-warning'},
    'VCC': {btnClass: 'btn-warning'},
    'VR': {btnClass: 'btn-warning'},
    'VJ': {btnClass: 'btn-warning'},
    'VD': {btnClass: 'btn-warning'},
    'VL': {btnClass: 'btn-warning'},
    'CNL': {btnClass: 'btn-warning'},
    'CSL': {btnClass: 'btn-warning'},
    'CAL': {btnClass: 'btn-warning'},
    'FNT': {btnClass: 'btn-warning'},
    'FCF': {btnClass: 'btn-warning'},
    'WCR': {btnClass: 'btn-warning'},
    'WEA': {btnClass: 'btn-warning'},
    'pCA': {btnClass: 'btn-warning'},
    'pBA': {btnClass: 'btn-warning'},
    'cRR': {btnClass: 'btn-warning'},
    'PJNG': {btnClass: 'btn-warning'},
    'VCP': {btnClass: 'btn-warning'},
    'VCD': {btnClass: 'btn-warning'},
    'VCL': {btnClass: 'btn-warning'},
    'PWO': {btnClass: 'btn-warning'},
    'POC': {btnClass: 'btn-warning'},
    'POF': {btnClass: 'btn-warning'},
    'PWR': {btnClass: 'btn-warning'},
    'FAM': {btnClass: 'btn-warning'},
}

// This is the dropdown options when you change a check status
export const checkChangeStatusList = [
    //{ value: 'N', label: 'N: new', group: STATUS_GROUP.NEW},
    { value: 'A', label: 'A: assigned', group: STATUS_GROUP.ASSIGNED },
    { value: 'OC', label: 'OC: owner-check', group: STATUS_GROUP.DISPOSING },
    // { value: 'SOA', label: 'SOA: stake-owner-action', group: STATUS_GROUP.SOA },
    //{ value: 'fST', label: 'fST: final-supportteam-comment', group: STATUS_GROUP.FST },
    { value: 'SD', label: 'SD: oc-sw-debug', group: STATUS_GROUP.DISPOSING},
    { value: 'RI', label: 'RI: oc-recipe-impr', group: STATUS_GROUP.DISPOSING},
    { value: 'ER', label: 'ER: oc-ext-recipe', group: STATUS_GROUP.DISPOSING },
    { value: 'OP', label: 'OP: oc-process', group:  STATUS_GROUP.DISPOSING},
    { value: 'MP', label: 'MP: manual-patch', group:  STATUS_GROUP.PATCHING},
    { value: 'PCF', label: 'PCF: passed-check-fail', group: STATUS_GROUP.PASS },
    { value: 'PW', label: 'PW: passed-waive', group: STATUS_GROUP.PASS},
    { value: 'PT', label: 'PT: passed-weakpoint', group: STATUS_GROUP.PASS},
    { value: 'PC', label: 'PC: passed-clean', group: STATUS_GROUP.PASS },
    { value: 'PP', label: 'PP: passed-patched', group: STATUS_GROUP.PASS},
    { value: 'PNR', label: 'PNR: passed-not-inspect-region', group: STATUS_GROUP.PASS },
    { value: 'PI', label: 'PI: passed-ignore', group: STATUS_GROUP.PASS },
    { value: 'FD', label: 'FD: fail-design', group: STATUS_GROUP.FAIL},
    { value: 'FR', label: 'FR: fail-recipe', group: STATUS_GROUP.FAIL },
    { value: 'FS', label: 'FS: fail-software', group: STATUS_GROUP.FAIL },
];

